// Curated habit icon set — 60 icons, grouped, each with a stable key stored on
// the habit row. Habits without a chosen icon fall back to keyword matching on
// the name, then to a generic spark.
import {
  Sunrise,
  Sun,
  MoonStar,
  AlarmClock,
  BedDouble,
  Bath,
  GlassWater,
  Droplets,
  Apple,
  Salad,
  ChefHat,
  UtensilsCrossed,
  Coffee,
  Dumbbell,
  Footprints,
  Bike,
  Waves,
  Mountain,
  Activity,
  HeartPulse,
  Trophy,
  Brain,
  Flower2,
  BookOpen,
  BookMarked,
  GraduationCap,
  Languages,
  PenLine,
  NotebookPen,
  Lightbulb,
  Code2,
  Briefcase,
  Target,
  ListChecks,
  CalendarCheck,
  Mail,
  Phone,
  Wallet,
  PiggyBank,
  Music,
  Camera,
  Palette,
  Smile,
  HandHeart,
  Users,
  Dog,
  Leaf,
  TreePine,
  PhoneOff,
  BellOff,
  Ban,
  Gamepad2,
  CigaretteOff,
  Pill,
  Home,
  Shirt,
  Sparkles,
  Timer,
  Flame,
  Rocket,
  type LucideIcon,
} from "lucide-react";

export type HabitIconDef = { key: string; label: string; Icon: LucideIcon };

/** The picker set — grouped loosely: routine, health, body, mind, work, life, quit. */
export const HABIT_ICONS: HabitIconDef[] = [
  // routine
  { key: "sunrise", label: "Morning", Icon: Sunrise },
  { key: "sun", label: "Midday", Icon: Sun },
  { key: "moon", label: "Night", Icon: MoonStar },
  { key: "alarm", label: "Wake up", Icon: AlarmClock },
  { key: "sleep", label: "Sleep", Icon: BedDouble },
  { key: "shower", label: "Shower", Icon: Bath },
  { key: "timer", label: "Deep work", Icon: Timer },
  { key: "streak", label: "Streak", Icon: Flame },
  // health
  { key: "water", label: "Water", Icon: GlassWater },
  { key: "hydrate", label: "Hydrate", Icon: Droplets },
  { key: "fruit", label: "Fruit", Icon: Apple },
  { key: "salad", label: "Eat clean", Icon: Salad },
  { key: "cook", label: "Cook", Icon: ChefHat },
  { key: "meal", label: "Meals", Icon: UtensilsCrossed },
  { key: "coffee", label: "Coffee", Icon: Coffee },
  { key: "meds", label: "Vitamins", Icon: Pill },
  { key: "heart", label: "Cardio", Icon: HeartPulse },
  // body
  { key: "gym", label: "Gym", Icon: Dumbbell },
  { key: "walk", label: "Walk / run", Icon: Footprints },
  { key: "bike", label: "Cycle", Icon: Bike },
  { key: "swim", label: "Swim", Icon: Waves },
  { key: "hike", label: "Hike", Icon: Mountain },
  { key: "stretch", label: "Stretch", Icon: Activity },
  { key: "sport", label: "Sport", Icon: Trophy },
  // mind
  { key: "meditate", label: "Meditate", Icon: Brain },
  { key: "yoga", label: "Yoga", Icon: Flower2 },
  { key: "read", label: "Read", Icon: BookOpen },
  { key: "scripture", label: "Scripture", Icon: BookMarked },
  { key: "study", label: "Study", Icon: GraduationCap },
  { key: "language", label: "Language", Icon: Languages },
  { key: "journal", label: "Journal", Icon: PenLine },
  { key: "notes", label: "Notes", Icon: NotebookPen },
  { key: "idea", label: "Ideas", Icon: Lightbulb },
  // work & money
  { key: "code", label: "Code", Icon: Code2 },
  { key: "work", label: "Work", Icon: Briefcase },
  { key: "goal", label: "Goal", Icon: Target },
  { key: "tasks", label: "Tasks", Icon: ListChecks },
  { key: "plan", label: "Plan day", Icon: CalendarCheck },
  { key: "inbox", label: "Inbox zero", Icon: Mail },
  { key: "call", label: "Call", Icon: Phone },
  { key: "budget", label: "Budget", Icon: Wallet },
  { key: "save", label: "Save", Icon: PiggyBank },
  { key: "launch", label: "Ship it", Icon: Rocket },
  // life & soul
  { key: "music", label: "Music", Icon: Music },
  { key: "photo", label: "Photo", Icon: Camera },
  { key: "art", label: "Create", Icon: Palette },
  { key: "gratitude", label: "Gratitude", Icon: Smile },
  { key: "kindness", label: "Kindness", Icon: HandHeart },
  { key: "family", label: "Family", Icon: Users },
  { key: "pet", label: "Pet", Icon: Dog },
  { key: "nature", label: "Nature", Icon: Leaf },
  { key: "garden", label: "Garden", Icon: TreePine },
  { key: "clean", label: "Clean", Icon: Home },
  { key: "laundry", label: "Laundry", Icon: Shirt },
  { key: "tidy", label: "Tidy", Icon: Sparkles },
  // quitting / limits
  { key: "nophone", label: "No phone", Icon: PhoneOff },
  { key: "nonotif", label: "No pings", Icon: BellOff },
  { key: "nogame", label: "Less gaming", Icon: Gamepad2 },
  { key: "nosmoke", label: "No smoking", Icon: CigaretteOff },
  { key: "quit", label: "Quit it", Icon: Ban },
];

const BY_KEY = new Map(HABIT_ICONS.map((d) => [d.key, d.Icon]));

// Name → icon guesses for habits created before icons existed (or added without one).
const KEYWORDS: [RegExp, string][] = [
  [/gym|lift|workout|push.?up|strength|train/i, "gym"],
  [/run|jog|walk|steps/i, "walk"],
  [/cycle|bike|cycling/i, "bike"],
  [/swim/i, "swim"],
  [/hike|trek/i, "hike"],
  [/stretch|mobility/i, "stretch"],
  [/yoga/i, "yoga"],
  [/meditat|mindful|breath/i, "meditate"],
  [/read|book|pages/i, "read"],
  [/quran|bible|gita|scripture|pray|prayer|namaz/i, "scripture"],
  [/study|learn|course|revise/i, "study"],
  [/language|duolingo|vocab/i, "language"],
  [/journal|diary|gratitude/i, "journal"],
  [/write|blog|notes/i, "notes"],
  [/code|program|leetcode|dsa|project/i, "code"],
  [/work|job|office/i, "work"],
  [/plan|schedule|review/i, "plan"],
  [/email|inbox/i, "inbox"],
  [/call|mom|dad|parent|family|friend/i, "call"],
  [/budget|expense|money|invest|save/i, "budget"],
  [/water|hydrate|litre|liter/i, "water"],
  [/fruit|apple/i, "fruit"],
  [/eat|diet|meal|protein|salad|junk/i, "salad"],
  [/cook/i, "cook"],
  [/coffee|caffeine/i, "coffee"],
  [/vitamin|supplement|med(s|icine)|pill/i, "meds"],
  [/sleep|bed(?!room)|10.?pm|11.?pm/i, "sleep"],
  [/wake|alarm|5.?am|6.?am/i, "alarm"],
  [/shower|bath|cold/i, "shower"],
  [/clean|chore|dishes|room/i, "clean"],
  [/laundry/i, "laundry"],
  [/music|guitar|piano|sing|practice/i, "music"],
  [/draw|paint|art|design|sketch/i, "art"],
  [/photo/i, "photo"],
  [/dog|cat|pet/i, "pet"],
  [/garden|plant/i, "garden"],
  [/nature|outside|sunlight/i, "nature"],
  [/no.?phone|screen.?time|scroll|instagram|reels|social/i, "nophone"],
  [/game|gaming/i, "nogame"],
  [/smok|vape/i, "nosmoke"],
  [/quit|stop|avoid|no /i, "quit"],
  [/focus|deep.?work|pomodoro/i, "timer"],
];

/** Resolve a habit's icon: explicit key → keyword guess → spark. */
export function iconFor(h: { icon?: string | null; name: string }): LucideIcon {
  if (h.icon) {
    const found = BY_KEY.get(h.icon);
    if (found) return found;
  }
  for (const [re, key] of KEYWORDS) {
    if (re.test(h.name)) return BY_KEY.get(key)!;
  }
  return Sparkles;
}
